const DATA={about:"data/about.json",news:"data/news.json",team:"data/team.json",projects:"data/projects.json",services:"data/services.json",equipment:"data/equipment.json",technologies:"data/technologies.json",resources:"data/resources.json",national:"data/collaborations_national.json",international:"data/collaborations_international.json",publications:"data/publications.json",contact:"data/contact.json"};
const safe=v=>(v??"").toString().trim();
async function getJSON(path,fallback=[]){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)return fallback;return await r.json()}catch{return fallback}}
function esc(s){return safe(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function iconSVG(kind){const icons={remote:`<svg viewBox="0 0 24 24"><path d="M4 17c4-4 8-8 16-10"/><path d="M7 6l4 4"/><path d="M14 3l4 4"/><circle cx="7" cy="17" r="2.5"/><path d="M17 13a5 5 0 0 1-5 5"/></svg>`,ai:`<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="5" r="2"/><circle cx="19" cy="9" r="2"/><circle cx="12" cy="19" r="2"/><circle cx="19" cy="17" r="2"/><path d="M6.5 10.7l4-4.2M13.8 5.8l3.4 2M6.8 13l3.7 4.4M13.9 18.4l3.2-1M13.6 6.5l4 8.7M6.9 11.5l10-2"/></svg>`,water:`<svg viewBox="0 0 24 24"><path d="M12 3s6 6.4 6 11a6 6 0 0 1-12 0c0-4.6 6-11 6-11z"/><path d="M9 15c1 1 2 1.5 3.5 1.5"/></svg>`,code:`<svg viewBox="0 0 24 24"><path d="M8 8l-4 4 4 4M16 8l4 4-4 4M14 4l-4 16"/></svg>`,file:`<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></svg>`};return icons[safe(kind).toLowerCase()]||icons.remote}
function getMedia(item){if(Array.isArray(item.media))return item.media;const src=safe(item.media||item.photo);return src?[{src,type:safe(item.media_type)||"image"}]:[]}
function mediaGallery(item,opts={}){const media=getMedia(item);if(!media.length)return"";const max=opts.max||media.length;const shown=media.slice(0,max);return `<div class="media-gallery ${media.length===1?'single':''}">${shown.map((m,i)=>m.type==="video"?`<video class="media-clickable" src="${esc(m.src)}" muted autoplay loop playsinline preload="metadata" data-gallery='${esc(JSON.stringify(media))}' data-index="${i}"></video>`:`<img class="media-clickable" src="${esc(m.src)}" alt="${esc(item.name)}" loading="lazy" data-gallery='${esc(JSON.stringify(media))}' data-index="${i}">`).join("")}${media.length>max?`<button class="gallery-more" data-open-gallery='${esc(JSON.stringify(media))}' data-index="${max}">+${media.length-max}</button>`:""}</div>`}
function linkButtons(item,defs){const out=[];for(const [key,label] of defs){const value=safe(item[key]);if(value)out.push(`<a href="${esc(value)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`)}return out.length?`<div class="card-links">${out.join("")}</div>`:""}
function empty(el,text){el.innerHTML=`<div class="empty-state">${text}</div>`}
function renderAbout(data){document.getElementById("about-intro").textContent=safe(data.intro);document.getElementById("about-mission").textContent=safe(data.mission);document.getElementById("about-vision").textContent=safe(data.vision);const el=document.getElementById("about-areas"),areas=data.areas||[];if(!areas.length)return empty(el,"Research areas will appear here.");el.innerHTML=areas.map(a=>`<article class="soft-card"><div class="serious-icon">${iconSVG(a.icon)}</div><h3>${esc(a.name)}</h3><p>${esc(a.summary)}</p></article>`).join("")}

let NEWS=[];
function populateNewsFilters(items){const y=document.getElementById("news-year"),m=document.getElementById("news-month");[...new Set(items.map(x=>safe(x.date).slice(0,4)).filter(Boolean))].sort((a,b)=>b-a).forEach(v=>y.insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`));const months=["January","February","March","April","May","June","July","August","September","October","November","December"];months.forEach((name,i)=>m.insertAdjacentHTML("beforeend",`<option value="${String(i+1).padStart(2,'0')}">${name}</option>`));y.addEventListener("change",renderNewsFiltered);m.addEventListener("change",renderNewsFiltered)}
function renderNewsFiltered(){const y=document.getElementById("news-year").value,m=document.getElementById("news-month").value;renderNews(NEWS.filter(n=>(y==="all"||safe(n.date).startsWith(y))&&(m==="all"||safe(n.date).slice(5,7)===m)))}
function renderNews(items){const el=document.getElementById("news-rail");items=[...items].sort((a,b)=>safe(b.date).localeCompare(safe(a.date)));if(!items.length)return empty(el,"No news matches the selected filters.");el.innerHTML=items.map(n=>`<article class="dynamic-card news-card">${mediaGallery(n,{max:3})}<div class="news-body"><div class="news-date">${esc(n.date)}${safe(n.type)?` · ${esc(n.type)}`:""}</div><h3>${esc(n.name)}</h3>${safe(n.summary)?`<p>${esc(n.summary)}</p>`:""}${linkButtons(n,[["link","Read more"]])}</div></article>`).join("")}

let PROJECTS=[],PROJECT_STATUS="all";
function projectState(p){const s=safe(p.status).toLowerCase();if(/ongoing|open|in progress|active|en ejecuci[oó]n/.test(s))return"open";if(/closed|completed|finished|terminated|cerrado|terminado|finalizado/.test(s))return"closed";return"other"}
function renderProjectsFiltered(){renderProjects(PROJECT_STATUS==="all"?PROJECTS:PROJECTS.filter(p=>projectState(p)===PROJECT_STATUS))}
function renderProjects(items){const el=document.getElementById("projects-rail");if(!items.length)return empty(el,"No projects match this filter.");el.innerHTML=items.map(p=>`<article class="dynamic-card project-card">${mediaGallery(p,{max:3})}<div class="card-top">${safe(p.type)?`<span class="tag">${esc(p.type)}</span>`:""}${safe(p.scope)?`<span class="tag">${esc(p.scope)}</span>`:""}${safe(p.status)?`<span class="tag ${projectState(p)==='open'?'status-active':'status-closed'}">${esc(p.status)}</span>`:""}</div><h3>${esc(p.name)}</h3>${safe(p.summary)?`<p>${esc(p.summary)}</p>`:""}<div class="meta">${safe(p.period)?`<div class="meta-item"><small>Period</small><strong>${esc(p.period)}</strong></div>`:""}${safe(p.role)?`<div class="meta-item"><small>Role</small><strong>${esc(p.role)}</strong></div>`:""}</div>${linkButtons(p,[["link","More information"],["project","Project"],["publications","Publications"],["results","Results"]])}</article>`).join("")}
function setupProjectFilters(){document.querySelectorAll("#project-status button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#project-status button").forEach(x=>x.classList.remove("active"));b.classList.add("active");PROJECT_STATUS=b.dataset.value;renderProjectsFiltered()}))}

function renderServices(items){const el=document.getElementById("services-rail");if(!items.length)return empty(el,"Services will appear automatically when folders are added to /Services.");el.innerHTML=items.map(s=>`<article class="soft-card dynamic-card service-card">${getMedia(s).length?mediaGallery(s,{max:3}):`<div class="serious-icon">${iconSVG(s.icon||"remote")}</div>`}<h3>${esc(s.name)}</h3>${safe(s.summary)?`<p>${esc(s.summary)}</p>`:""}${linkButtons(s,[["link","More information"],["website","More information"]])}</article>`).join("")}

const GROUPS={"lab leader":{key:"leader",label:"Lab Leader",rank:0},"leader":{key:"leader",label:"Lab Leader",rank:0},"researcher":{key:"researchers",label:"Researchers",rank:1},"researchers":{key:"researchers",label:"Researchers",rank:1},"postgraduate student":{key:"postgraduate",label:"Postgraduate Students",rank:2},"postgraduate students":{key:"postgraduate",label:"Postgraduate Students",rank:2},"undergraduate student":{key:"undergraduate",label:"Undergraduate Students",rank:3},"undergraduate students":{key:"undergraduate",label:"Undergraduate Students",rank:3},"other":{key:"other",label:"Other Members",rank:4}};
function memberGroup(p){const explicit=safe(p.group).toLowerCase();if(GROUPS[explicit])return GROUPS[explicit];const position=`${safe(p.position)} ${safe(p.studies)}`.toLowerCase();if(/principal investigator|lab leader|director.*lab|head.*lab/.test(position))return GROUPS["lab leader"];if(/researcher|investigator|investigador|academic|professor|postdoc/.test(position))return GROUPS.researcher;if(/ph\.d|msc|m\.sc|master|mag[ií]ster|doctoral|postgraduate|postgrado|thesis student/.test(position))return GROUPS["postgraduate student"];if(/undergraduate|pregrado|bachelor|tesista/.test(position))return GROUPS["undergraduate student"];return GROUPS.other}
function personCard(p,flag=""){const initials=safe(p.name).split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();const media=getMedia(p),first=media[0];const avatar=first?(first.type==="video"?`<video class="media-clickable" src="${esc(first.src)}" muted autoplay loop playsinline data-gallery='${esc(JSON.stringify(media))}' data-index="0"></video>`:`<img class="media-clickable" src="${esc(first.src)}" alt="${esc(p.name)}" data-gallery='${esc(JSON.stringify(media))}' data-index="0">`):esc(initials);const keywords=(p.keywords||[]).map(k=>`<span class="keyword">${esc(k)}</span>`).join("");const extra=media.length>1?`<div class="profile-extra-media">${media.slice(1,4).map((m,i)=>m.type==="video"?`<video class="media-clickable" src="${esc(m.src)}" muted autoplay loop playsinline data-gallery='${esc(JSON.stringify(media))}' data-index="${i+1}"></video>`:`<img class="media-clickable" src="${esc(m.src)}" data-gallery='${esc(JSON.stringify(media))}' data-index="${i+1}">`).join("")}</div>`:"";return `<article class="dynamic-card person-card"><div class="person-head"><div class="person-media">${avatar}</div><div><h3>${esc(p.name)}${flag?`<span class="flag">${flag}</span>`:""}</h3>${safe(p.position)?`<div class="person-role">${esc(p.position)}</div>`:""}${safe(p.studies)?`<div class="person-org">${esc(p.studies)}</div>`:""}${safe(p.organization)?`<div class="person-org">${esc(p.organization)}</div>`:""}</div></div>${safe(p.summary)?`<p>${esc(p.summary)}</p>`:""}${keywords?`<div class="keywords">${keywords}</div>`:""}${extra}${linkButtons(p,[["linkedin","LinkedIn"],["researchgate","ResearchGate"],["orcid","ORCID"],["website","Website"]])}</article>`}
function groupRail(id,cards){return `<div class="group-rail-head"><div class="rail-controls"><button data-scroll="${id}" data-dir="-1">←</button><button data-scroll="${id}" data-dir="1">→</button></div></div><div id="${id}" class="horizontal-rail group-rail">${cards}</div>`}
function renderTeam(items){const el=document.getElementById("team-groups");if(!items.length)return empty(el,"Team members will appear automatically when folders are added to /Team.");const groups=new Map();items.forEach(p=>{const g=memberGroup(p);if(!groups.has(g.key))groups.set(g.key,{...g,items:[]});groups.get(g.key).items.push(p)});const ordered=[...groups.values()].sort((a,b)=>a.rank-b.rank);el.innerHTML=ordered.map(g=>{const id=`team-${g.key}-rail`;const cards=g.items.sort((a,b)=>safe(a.name).localeCompare(safe(b.name))).map(p=>personCard(p)).join("");return `<details class="group-accordion" ${g.key==="leader"?"open":""}><summary><span>${g.label}</span><span>${g.items.length}</span></summary><div class="group-content">${groupRail(id,cards)}</div></details>`}).join("");setupRails()}

const COUNTRY_FLAGS={chile:"🇨🇱",italy:"🇮🇹",italia:"🇮🇹",spain:"🇪🇸",españa:"🇪🇸",germany:"🇩🇪",alemania:"🇩🇪",france:"🇫🇷",francia:"🇫🇷",usa:"🇺🇸","united states":"🇺🇸",canada:"🇨🇦",brazil:"🇧🇷",brasil:"🇧🇷",argentina:"🇦🇷",peru:"🇵🇪",perú:"🇵🇪",ecuador:"🇪🇨",colombia:"🇨🇴",mexico:"🇲🇽",méxico:"🇲🇽",uk:"🇬🇧","united kingdom":"🇬🇧",portugal:"🇵🇹",australia:"🇦🇺",japan:"🇯🇵",japón:"🇯🇵"};
function countryFlag(country){return COUNTRY_FLAGS[safe(country).toLowerCase()]||"🌐"}
function renderCollaborations(national,international){const el=document.getElementById("collaboration-groups"),groups=[{key:"national",label:"National Collaborations",items:national},{key:"international",label:"International Collaborations",items:international}];el.innerHTML=groups.map(g=>{const id=`collab-${g.key}-rail`;const cards=g.items.map(c=>personCard(c,countryFlag(c.country))).join("");return `<details class="group-accordion"><summary><span>${g.label}</span><span>${g.items.length}</span></summary><div class="group-content">${g.items.length?groupRail(id,cards):`<div class="empty-state">No collaborators added yet.</div>`}</div></details>`}).join("");setupRails()}

function renderEquipment(items){const el=document.getElementById("equipment-rail");if(!items.length)return empty(el,"Equipment will appear automatically when folders are added to /Equipment.");el.innerHTML=items.map(e=>`<article class="dynamic-card equipment-card">${getMedia(e).length?mediaGallery(e,{max:3}):`<div class="equipment-placeholder">◇</div>`}<div class="equipment-body"><h3>${esc(e.name)}</h3>${safe(e.model)?`<div class="person-role">${esc(e.model)}</div>`:""}${safe(e.summary)?`<p>${esc(e.summary)}</p>`:""}${linkButtons(e,[["link","More information"],["website","More information"]])}</div></article>`).join("")}
function renderTechnologies(items){const el=document.getElementById("technologies-rail");if(!items.length)return empty(el,"Software and digital developments will appear automatically when folders are added to /Technologies.");el.innerHTML=items.map(t=>`<article class="dynamic-card technology-card">${getMedia(t).length?mediaGallery(t,{max:3}):`<div class="equipment-placeholder">${iconSVG("code")}</div>`}<div class="technology-body"><div class="card-top">${safe(t.type)?`<span class="tag">${esc(t.type)}</span>`:""}</div><h3>${esc(t.name)}</h3>${safe(t.version)?`<div class="person-role">Version ${esc(t.version)}</div>`:""}${safe(t.summary)?`<p>${esc(t.summary)}</p>`:""}${linkButtons(t,[["link","Open technology"],["repository","Repository"],["documentation","Documentation"]])}</div></article>`).join("")}
function renderResources(items){const el=document.getElementById("resources-rail");if(!items.length)return empty(el,"Manuals, classes and other resources will appear automatically when folders are added to /Resources.");el.innerHTML=items.map(r=>{const files=Array.isArray(r.downloads)&&r.downloads.length?r.downloads:[safe(r.download)].filter(Boolean);const fileLinks=files.map((f,i)=>`<a href="${esc(f)}" target="_blank" rel="noopener noreferrer">${files.length>1?`File ${i+1}`:'Open file'} ↗</a>`).join("");return `<article class="dynamic-card resource-card">${getMedia(r).length?mediaGallery(r,{max:3}):`<div class="equipment-placeholder">${iconSVG("file")}</div>`}<div class="resource-body"><div class="card-top">${safe(r.type)?`<span class="tag">${esc(r.type)}</span>`:""}${safe(r.year)?`<span class="tag">${esc(r.year)}</span>`:""}</div><h3>${esc(r.name)}</h3>${safe(r.summary)?`<p>${esc(r.summary)}</p>`:""}${linkButtons(r,[["link","Open resource"]])}${fileLinks?`<div class="card-links">${fileLinks}</div>`:""}</div></article>`}).join("")}

let PUBLICATIONS=[],PUB_SHOW_ALL=false;
function normalizeDOI(v){let doi=safe(v).replace(/^https?:\/\/(dx\.)?doi\.org\//i,"").replace(/^doi:\s*/i,"");return doi?`https://doi.org/${doi}`:""}
function populatePublicationYears(items){const s=document.getElementById("publication-year");[...new Set(items.map(x=>safe(x.year)).filter(Boolean))].sort((a,b)=>Number(b)-Number(a)).forEach(v=>s.insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`));s.addEventListener("change",()=>{PUB_SHOW_ALL=false;renderPublicationsFiltered()})}
function renderPublicationsFiltered(){const y=document.getElementById("publication-year").value;let items=PUBLICATIONS.filter(p=>y==="all"||safe(p.year)===y);items=[...items].sort((a,b)=>Number(b.year||0)-Number(a.year||0)||safe(a.name).localeCompare(safe(b.name)));const shown=PUB_SHOW_ALL?items:items.slice(0,3);renderPublications(shown);const btn=document.getElementById("publications-toggle");btn.style.display=items.length>3?"inline-flex":"none";btn.textContent=PUB_SHOW_ALL?"Show only latest 3 −":"View all publications +"}
function renderPublications(items){const el=document.getElementById("publications-list");if(!items.length)return empty(el,"No publications match this filter.");el.innerHTML=items.map(p=>{const doi=normalizeDOI(p.doi),link=safe(p.link)||doi;return `<article class="publication-item"><div class="publication-year">${esc(p.year)}</div><div><div class="publication-title">${esc(p.name)}</div>${safe(p.authors)?`<div class="publication-authors">${esc(p.authors)}</div>`:""}${safe(p.journal)?`<div class="publication-journal">${esc(p.journal)}</div>`:""}</div><div class="publication-actions">${doi?`<a href="${esc(doi)}" target="_blank" rel="noopener noreferrer">DOI ↗</a>`:""}${link&&link!==doi?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer">Link ↗</a>`:""}</div></article>`}).join("")}

function renderContact(c){const email=safe(c.email)||"syepez@udec.cl";document.getElementById("contact-email").textContent=email;document.getElementById("email-button").href=`mailto:${email}?subject=HydroGeoAI%20Lab%20-%20Contact&body=Hello%20HydroGeoAI%20Lab%2C%0A%0AI%20would%20like%20to%20contact%20you%20regarding%3A%0A%0A`;document.getElementById("contact-location").textContent=safe(c.location)||"Concepción, Chile";const lat=safe(c.latitude)||"-36.834495",lon=safe(c.longitude)||"-73.032547";document.getElementById("map-frame").src=`https://www.google.com/maps?q=${lat},${lon}&z=16&output=embed`;document.getElementById("map-link").href=safe(c.maplink)||"https://maps.app.goo.gl/EthMW9VcD7aecfzE7";const socials=[["instagram","Instagram"],["facebook","Facebook"],["linkedin","LinkedIn"],["youtube","YouTube"],["x","X"],["researchgate","ResearchGate"],["website","Website"]];document.getElementById("social-links").innerHTML=socials.filter(([k])=>safe(c[k])).map(([k,l])=>`<a href="${esc(c[k])}" target="_blank" rel="noopener noreferrer">${l} ↗</a>`).join("")}
function setupRails(){document.querySelectorAll("[data-scroll]").forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound="1";btn.addEventListener("click",()=>{const rail=document.getElementById(btn.dataset.scroll);rail?.scrollBy({left:Number(btn.dataset.dir)*380,behavior:"smooth"})})})}
function setupMediaModal(){const modal=document.getElementById("media-modal"),stage=document.getElementById("media-stage"),close=document.getElementById("media-close");let gallery=[],idx=0;function show(){const m=gallery[idx];if(!m)return;stage.innerHTML=`<button class="modal-nav modal-prev" aria-label="Previous">‹</button>${m.type==="video"?`<video src="${esc(m.src)}" controls autoplay></video>`:`<img src="${esc(m.src)}" alt="Expanded media">`}<button class="modal-nav modal-next" aria-label="Next">›</button><div class="modal-counter">${idx+1} / ${gallery.length}</div>`;stage.querySelector('.modal-prev').onclick=()=>{idx=(idx-1+gallery.length)%gallery.length;show()};stage.querySelector('.modal-next').onclick=()=>{idx=(idx+1)%gallery.length;show()}}
function open(items,start=0){gallery=items;idx=Math.max(0,Math.min(start,items.length-1));show();modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function shut(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");stage.innerHTML="";document.body.style.overflow=""}
document.addEventListener("click",e=>{const t=e.target;if(t.matches(".media-clickable")){try{open(JSON.parse(t.dataset.gallery||'[]'),Number(t.dataset.index||0))}catch{open([{src:t.currentSrc||t.src,type:t.tagName==='VIDEO'?'video':'image'}],0)}}else if(t.matches(".gallery-more")){try{open(JSON.parse(t.dataset.openGallery||'[]'),Number(t.dataset.index||0))}catch{}}});close.addEventListener("click",shut);modal.addEventListener("click",e=>{if(e.target===modal)shut()});document.addEventListener("keydown",e=>{if(!modal.classList.contains('open'))return;if(e.key==='Escape')shut();if(e.key==='ArrowLeft'){idx=(idx-1+gallery.length)%gallery.length;show()}if(e.key==='ArrowRight'){idx=(idx+1)%gallery.length;show()}})}
async function init(){const [about,news,projects,services,team,national,international,equipment,technologies,resources,publications,contact]=await Promise.all([getJSON(DATA.about,{}),getJSON(DATA.news),getJSON(DATA.projects),getJSON(DATA.services),getJSON(DATA.team),getJSON(DATA.national),getJSON(DATA.international),getJSON(DATA.equipment),getJSON(DATA.technologies),getJSON(DATA.resources),getJSON(DATA.publications),getJSON(DATA.contact,{})]);renderAbout(about);NEWS=news;renderNews(NEWS);populateNewsFilters(NEWS);PROJECTS=projects;renderProjectsFiltered();setupProjectFilters();renderServices(services);renderTeam(team);renderCollaborations(national,international);renderEquipment(equipment);renderTechnologies(technologies);renderResources(resources);PUBLICATIONS=publications;populatePublicationYears(PUBLICATIONS);renderPublicationsFiltered();document.getElementById("publications-toggle").addEventListener("click",()=>{PUB_SHOW_ALL=!PUB_SHOW_ALL;renderPublicationsFiltered()});renderContact(contact);setupRails();setupMediaModal()}
init();
