const DATA={
  about:"data/about.json",news:"data/news.json",team:"data/team.json",projects:"data/projects.json",
  services:"data/services.json",courses:"data/courses.json",equipment:"data/equipment.json",
  technologies:"data/technologies.json",resources:"data/resources.json",
  national:"data/collaborations_national.json",international:"data/collaborations_international.json",
  publications:"data/publications.json",contact:"data/contact.json"
};

const safe=v=>(v??"").toString().trim();
async function getJSON(path,fallback=[]){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)return fallback;return await r.json()}catch{return fallback}}
function esc(s){return safe(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function assetURL(src){const v=safe(src);if(!v)return"";if(/^(https?:|mailto:|tel:|data:|blob:)/i.test(v))return v;return v.split('/').map(part=>encodeURIComponent(part)).join('/').replace(/%23U([0-9A-Fa-f]{4})/g,'%23U$1')}
function splitValues(value){return safe(value).split(/[;\n|]+/).map(x=>x.trim()).filter(Boolean)}
function plural(n,one,many){return `${n} ${n===1?one:many}`}
function uniqueValues(items,key){return [...new Set(items.map(x=>safe(x[key])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'}))}
function setOptions(select,values,allLabel){if(!select)return;select.innerHTML=`<option value="all">${esc(allLabel)}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}

function iconSVG(kind){const icons={remote:`<svg viewBox="0 0 24 24"><path d="M4 17c4-4 8-8 16-10"/><path d="M7 6l4 4"/><path d="M14 3l4 4"/><circle cx="7" cy="17" r="2.5"/><path d="M17 13a5 5 0 0 1-5 5"/></svg>`,ai:`<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="5" r="2"/><circle cx="19" cy="9" r="2"/><circle cx="12" cy="19" r="2"/><circle cx="19" cy="17" r="2"/><path d="M6.5 10.7l4-4.2M13.8 5.8l3.4 2M6.8 13l3.7 4.4M13.9 18.4l3.2-1M13.6 6.5l4 8.7M6.9 11.5l10-2"/></svg>`,water:`<svg viewBox="0 0 24 24"><path d="M12 3s6 6.4 6 11a6 6 0 0 1-12 0c0-4.6 6-11 6-11z"/><path d="M9 15c1 1 2 1.5 3.5 1.5"/></svg>`,code:`<svg viewBox="0 0 24 24"><path d="M8 8l-4 4 4 4M16 8l4 4-4 4M14 4l-4 16"/></svg>`,file:`<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></svg>`,course:`<svg viewBox="0 0 24 24"><path d="M3 6l9-3 9 3-9 3z"/><path d="M6 8.5V14c0 2 3 4 6 4s6-2 6-4V8.5"/><path d="M21 7v7"/></svg>`};return icons[safe(kind).toLowerCase()]||icons.remote}

function getMedia(item){if(Array.isArray(item.media))return item.media;const src=safe(item.media||item.photo);return src?[{src,type:safe(item.media_type)||"image"}]:[]}
function mediaGallery(item){
  const media=getMedia(item);if(!media.length)return"";
  const payload=esc(JSON.stringify(media));
  return `<div class="media-carousel" data-media-carousel data-count="${media.length}">
    <div class="media-carousel-track">${media.map((m,i)=>m.type==="video"?`<video class="media-slide media-clickable ${i===0?'active':''}" src="${esc(assetURL(m.src))}" muted loop playsinline preload="metadata" data-gallery='${payload}' data-index="${i}"></video>`:`<img class="media-slide media-clickable ${i===0?'active':''}" src="${esc(assetURL(m.src))}" alt="${esc(item.name)}" loading="lazy" data-gallery='${payload}' data-index="${i}">`).join("")}</div>
    ${media.length>1?`<button class="media-inline-nav media-inline-prev" type="button" aria-label="Previous media">‹</button><button class="media-inline-nav media-inline-next" type="button" aria-label="Next media">›</button><div class="media-inline-counter"><span>1</span> / ${media.length}</div>`:""}
  </div>`;
}
function mediaGalleryCompact(item){const m=getMedia(item);return m.length?mediaGallery(item):""}

function linkButtons(item,defs){
  const out=[];
  for(const [key,label] of defs){
    const values=splitValues(item[key]);
    values.forEach((value,i)=>out.push(`<a href="${esc(assetURL(value))}" target="_blank" rel="noopener noreferrer">${esc(values.length>1?`${label} ${i+1}`:label)} ↗</a>`));
  }
  return out.length?`<div class="card-links">${out.join("")}</div>`:"";
}
function empty(el,text){el.innerHTML=`<div class="empty-state">${esc(text)}</div>`}
function resultCount(id,n,label){const el=document.getElementById(id);if(el)el.textContent=plural(n,label,`${label}s`)}

function renderAbout(data){document.getElementById("about-intro").textContent=safe(data.intro);document.getElementById("about-mission").textContent=safe(data.mission);document.getElementById("about-vision").textContent=safe(data.vision);const el=document.getElementById("about-areas"),areas=data.areas||[];if(!areas.length)return empty(el,"Research areas will appear here.");el.innerHTML=areas.map(a=>`<article class="soft-card"><div class="serious-icon">${iconSVG(a.icon)}</div><h3>${esc(a.name)}</h3><p>${esc(a.summary)}</p></article>`).join("")}

let NEWS=[];
function populateNewsFilters(items){const y=document.getElementById("news-year"),m=document.getElementById("news-month");setOptions(y,[...new Set(items.map(x=>safe(x.date).slice(0,4)).filter(Boolean))].sort((a,b)=>b-a),"All years");const months=["January","February","March","April","May","June","July","August","September","October","November","December"];m.innerHTML='<option value="all">All months</option>'+months.map((name,i)=>`<option value="${String(i+1).padStart(2,'0')}">${name}</option>`).join('');y.addEventListener("change",renderNewsFiltered);m.addEventListener("change",renderNewsFiltered)}
function renderNewsFiltered(){const y=document.getElementById("news-year").value,m=document.getElementById("news-month").value;renderNews(NEWS.filter(n=>(y==="all"||safe(n.date).startsWith(y))&&(m==="all"||safe(n.date).slice(5,7)===m)))}
function renderNews(items){const el=document.getElementById("news-rail");items=[...items].sort((a,b)=>safe(b.date).localeCompare(safe(a.date)));el.scrollLeft=0;if(!items.length)return empty(el,"No news matches the selected filters.");el.innerHTML=items.map(n=>`<article class="dynamic-card news-card">${mediaGallery(n)}<div class="news-body"><div class="news-date">${esc(n.date)}${safe(n.type)?` · ${esc(n.type)}`:""}</div><h3>${esc(n.name)}</h3>${safe(n.summary)?`<p>${esc(n.summary)}</p>`:""}${linkButtons(n,[["link","Read more"],["publications","Publication"]])}</div></article>`).join("");enhanceDynamicUI()}

let PROJECTS=[];
function projectState(p){const s=safe(p.status).toLowerCase();if(/open|ongoing|in progress|active|en ejecuci[oó]n/.test(s))return"open";if(/closed|completed|finished|terminated|cerrado|terminado|finalizado/.test(s))return"closed";return"other"}
function populateProjectFilters(items){setOptions(document.getElementById('project-type'),uniqueValues(items,'type'),'All types');setOptions(document.getElementById('project-status'),uniqueValues(items,'status'),'All statuses');['project-type','project-status'].forEach(id=>document.getElementById(id).addEventListener('change',renderProjectsFiltered))}
function projectFiltered(){const t=document.getElementById('project-type').value,s=document.getElementById('project-status').value;return PROJECTS.filter(p=>(t==='all'||safe(p.type)===t)&&(s==='all'||safe(p.status)===s))}
function renderProjectsFiltered(){const items=projectFiltered();resultCount('project-count',items.length,'project');renderProjects(items);const focused=document.getElementById('project-focus');if(items.length===1&&(document.getElementById('project-type').value!=='all'||document.getElementById('project-status').value!=='all'))renderProjectFocus(items[0]);else if(focused)focused.hidden=true}
function projectCard(p,i){return `<article class="dynamic-card project-card" data-project-index="${i}">${mediaGallery(p)}<div class="card-top">${safe(p.type)?`<span class="tag">${esc(p.type)}</span>`:""}${safe(p.scope)?`<span class="tag">${esc(p.scope)}</span>`:""}${safe(p.status)?`<span class="tag ${projectState(p)==='open'?'status-active':projectState(p)==='closed'?'status-closed':''}">${esc(p.status)}</span>`:""}</div><h3>${esc(p.name)}</h3>${safe(p.summary)?`<p>${esc(p.summary)}</p>`:""}<div class="meta">${safe(p.period)?`<div class="meta-item"><small>Period</small><strong>${esc(p.period)}</strong></div>`:""}${safe(p.role)?`<div class="meta-item"><small>Role</small><strong>${esc(p.role)}</strong></div>`:""}</div><button class="detail-button" type="button" data-focus-project="${i}">View details +</button>${linkButtons(p,[["link","More information"],["project","Project"],["publications","Publication"],["results","Result"]])}</article>`}
function renderProjects(items){const el=document.getElementById("projects-rail");el.scrollLeft=0;if(!items.length)return empty(el,"No projects match these filters.");el.innerHTML=items.map((p,i)=>projectCard(p,i)).join("");el.querySelectorAll('[data-focus-project]').forEach(b=>b.addEventListener('click',()=>renderProjectFocus(items[Number(b.dataset.focusProject)])));enhanceDynamicUI()}
function renderProjectFocus(p){const el=document.getElementById('project-focus');if(!el)return;el.hidden=false;el.innerHTML=`<button class="focus-close" type="button" aria-label="Close details">×</button><div class="focus-grid"><div>${mediaGalleryCompact(p)||`<div class="focus-placeholder">${iconSVG('remote')}</div>`}</div><div><div class="card-top">${safe(p.type)?`<span class="tag">${esc(p.type)}</span>`:""}${safe(p.status)?`<span class="tag">${esc(p.status)}</span>`:""}</div><h3>${esc(p.name)}</h3>${safe(p.summary)?`<p>${esc(p.summary)}</p>`:""}<div class="meta">${safe(p.scope)?`<div class="meta-item"><small>Scope</small><strong>${esc(p.scope)}</strong></div>`:""}${safe(p.period)?`<div class="meta-item"><small>Period</small><strong>${esc(p.period)}</strong></div>`:""}${safe(p.role)?`<div class="meta-item"><small>Role</small><strong>${esc(p.role)}</strong></div>`:""}</div>${linkButtons(p,[["link","More information"],["project","Project"],["publications","Publication"],["results","Result"]])}</div></div>`;el.querySelector('.focus-close').onclick=()=>el.hidden=true;enhanceDynamicUI();el.scrollIntoView({behavior:'smooth',block:'nearest'})}

let SERVICES=[];
function populateServiceFilters(items){setOptions(document.getElementById('service-type'),uniqueValues(items,'type'),'All services');document.getElementById('service-type').addEventListener('change',renderServicesFiltered)}
function renderServicesFiltered(){const type=document.getElementById('service-type').value,items=SERVICES.filter(s=>type==='all'||safe(s.type)===type);resultCount('service-count',items.length,'service');renderServices(items);const focus=document.getElementById('service-focus');if(type!=='all'&&items.length===1)renderServiceFocus(items[0]);else if(focus)focus.hidden=true}
function renderServices(items){const el=document.getElementById("services-rail");el.scrollLeft=0;if(!items.length)return empty(el,"Services will appear automatically when folders are added to /Services.");el.innerHTML=items.map((s,i)=>`<article class="soft-card dynamic-card service-card">${getMedia(s).length?mediaGallery(s):`<div class="serious-icon">${iconSVG(s.icon||"remote")}</div>`}<div class="card-top">${safe(s.type)?`<span class="tag">${esc(s.type)}</span>`:""}</div><h3>${esc(s.name)}</h3>${safe(s.summary)?`<p>${esc(s.summary)}</p>`:""}<button class="detail-button" type="button" data-focus-service="${i}">View details +</button>${linkButtons(s,[["link","More information"],["website","Website"],["publications","Publication"],["documentation","Documentation"]])}</article>`).join("");el.querySelectorAll('[data-focus-service]').forEach(b=>b.addEventListener('click',()=>renderServiceFocus(items[Number(b.dataset.focusService)])));enhanceDynamicUI()}
function renderServiceFocus(s){const el=document.getElementById('service-focus');if(!el)return;el.hidden=false;el.innerHTML=`<button class="focus-close" type="button" aria-label="Close details">×</button><div class="focus-grid"><div>${getMedia(s).length?mediaGallery(s):`<div class="focus-placeholder">${iconSVG(s.icon||'remote')}</div>`}</div><div>${safe(s.type)?`<div class="card-top"><span class="tag">${esc(s.type)}</span></div>`:""}<h3>${esc(s.name)}</h3>${safe(s.summary)?`<p>${esc(s.summary)}</p>`:""}${linkButtons(s,[["link","More information"],["website","Website"],["publications","Publication"],["documentation","Documentation"]])}</div></div>`;el.querySelector('.focus-close').onclick=()=>el.hidden=true;enhanceDynamicUI();el.scrollIntoView({behavior:'smooth',block:'nearest'})}

let COURSES=[];
function populateCourseFilters(items){setOptions(document.getElementById('course-topic'),uniqueValues(items,'topic'),'All topics');setOptions(document.getElementById('course-level'),uniqueValues(items,'level'),'All levels');setOptions(document.getElementById('course-format'),uniqueValues(items,'format'),'All formats');setOptions(document.getElementById('course-status'),uniqueValues(items,'status'),'All statuses');['course-topic','course-level','course-format','course-status'].forEach(id=>document.getElementById(id).addEventListener('change',renderCoursesFiltered))}
function courseFiltered(){const vals={topic:document.getElementById('course-topic').value,level:document.getElementById('course-level').value,format:document.getElementById('course-format').value,status:document.getElementById('course-status').value};return COURSES.filter(c=>Object.entries(vals).every(([k,v])=>v==='all'||safe(c[k])===v))}
function renderCoursesFiltered(){const items=courseFiltered();resultCount('course-count',items.length,'course');renderCourses(items);const active=['course-topic','course-level','course-format','course-status'].some(id=>document.getElementById(id).value!=='all'),focus=document.getElementById('course-focus');if(active&&items.length===1)renderCourseFocus(items[0]);else if(focus)focus.hidden=true}
function courseMeta(c){return `${safe(c.level)?`<div class="meta-item"><small>Level</small><strong>${esc(c.level)}</strong></div>`:""}${safe(c.format)?`<div class="meta-item"><small>Format</small><strong>${esc(c.format)}</strong></div>`:""}${safe(c.duration)?`<div class="meta-item"><small>Duration</small><strong>${esc(c.duration)}</strong></div>`:""}${safe(c.price)?`<div class="meta-item"><small>Price</small><strong>${esc(c.price)}</strong></div>`:""}${safe(c.start)?`<div class="meta-item"><small>Start</small><strong>${esc(c.start)}</strong></div>`:""}${safe(c.instructor)?`<div class="meta-item"><small>Instructor</small><strong>${esc(c.instructor)}</strong></div>`:""}`}
function renderCourses(items){const el=document.getElementById('courses-rail');el.scrollLeft=0;if(!items.length)return empty(el,"New HydroGeoAI Lab courses and workshops will appear here soon.");el.innerHTML=items.map((c,i)=>`<article class="dynamic-card course-card">${getMedia(c).length?mediaGallery(c):`<div class="course-placeholder">${iconSVG('course')}</div>`}<div class="card-top">${safe(c.type)?`<span class="tag">${esc(c.type)}</span>`:""}${safe(c.topic)?`<span class="tag">${esc(c.topic)}</span>`:""}${safe(c.status)?`<span class="tag ${/open/i.test(c.status)?'status-active':/closed/i.test(c.status)?'status-closed':''}">${esc(c.status)}</span>`:""}</div><h3>${esc(c.name)}</h3>${safe(c.summary)?`<p>${esc(c.summary)}</p>`:""}<div class="meta">${courseMeta(c)}</div><button class="detail-button" type="button" data-focus-course="${i}">View course +</button>${linkButtons(c,[["registration","Register"],["link","Course page"],["syllabus","Syllabus"],["documentation","Documentation"]])}</article>`).join('');el.querySelectorAll('[data-focus-course]').forEach(b=>b.addEventListener('click',()=>renderCourseFocus(items[Number(b.dataset.focusCourse)])));enhanceDynamicUI()}
function renderCourseFocus(c){const el=document.getElementById('course-focus');if(!el)return;el.hidden=false;el.innerHTML=`<button class="focus-close" type="button" aria-label="Close details">×</button><div class="focus-grid"><div>${getMedia(c).length?mediaGallery(c):`<div class="focus-placeholder">${iconSVG('course')}</div>`}</div><div><div class="card-top">${safe(c.type)?`<span class="tag">${esc(c.type)}</span>`:""}${safe(c.topic)?`<span class="tag">${esc(c.topic)}</span>`:""}${safe(c.status)?`<span class="tag">${esc(c.status)}</span>`:""}</div><h3>${esc(c.name)}</h3>${safe(c.summary)?`<p>${esc(c.summary)}</p>`:""}<div class="meta">${courseMeta(c)}</div>${linkButtons(c,[["registration","Register"],["link","Course page"],["syllabus","Syllabus"],["documentation","Documentation"]])}</div></div>`;el.querySelector('.focus-close').onclick=()=>el.hidden=true;enhanceDynamicUI();el.scrollIntoView({behavior:'smooth',block:'nearest'})}

const GROUPS={"lab leader":{key:"leader",label:"Lab Leader",rank:0},"leader":{key:"leader",label:"Lab Leader",rank:0},"researcher":{key:"researchers",label:"Researchers",rank:1},"researchers":{key:"researchers",label:"Researchers",rank:1},"postgraduate student":{key:"postgraduate",label:"Postgraduate Students",rank:2},"postgraduate students":{key:"postgraduate",label:"Postgraduate Students",rank:2},"undergraduate student":{key:"undergraduate",label:"Undergraduate Students",rank:3},"undergraduate students":{key:"undergraduate",label:"Undergraduate Students",rank:3},"other":{key:"other",label:"Other Members",rank:4}};
function memberGroup(p){const explicit=safe(p.group).toLowerCase();if(GROUPS[explicit])return GROUPS[explicit];const position=`${safe(p.position)} ${safe(p.studies)}`.toLowerCase();if(/principal investigator|lab leader|director.*lab|head.*lab/.test(position))return GROUPS["lab leader"];if(/researcher|investigator|investigador|academic|professor|postdoc/.test(position))return GROUPS.researcher;if(/ph\.d|msc|m\.sc|master|mag[ií]ster|doctoral|postgraduate|postgrado|thesis student/.test(position))return GROUPS["postgraduate student"];if(/undergraduate|pregrado|bachelor|tesista/.test(position))return GROUPS["undergraduate student"];return GROUPS.other}
function personCard(p,flag=""){const initials=safe(p.name).split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();const media=getMedia(p),first=media[0];const avatar=first?(first.type==="video"?`<video class="media-clickable" src="${esc(assetURL(first.src))}" muted autoplay loop playsinline data-gallery='${esc(JSON.stringify(media))}' data-index="0"></video>`:`<img class="media-clickable" src="${esc(assetURL(first.src))}" alt="${esc(p.name)}" data-gallery='${esc(JSON.stringify(media))}' data-index="0">`):esc(initials);const keywords=(p.keywords||[]).map(k=>`<span class="keyword">${esc(k)}</span>`).join("");return `<article class="dynamic-card person-card"><div class="person-head"><div class="person-media">${avatar}</div><div><h3>${esc(p.name)}${flag?`<span class="flag">${flag}</span>`:""}</h3>${safe(p.position)?`<div class="person-role">${esc(p.position)}</div>`:""}${safe(p.studies)?`<div class="person-org">${esc(p.studies)}</div>`:""}${safe(p.organization)?`<div class="person-org">${esc(p.organization)}</div>`:""}</div></div>${safe(p.summary)?`<p>${esc(p.summary)}</p>`:""}${keywords?`<div class="keywords">${keywords}</div>`:""}${media.length>1?`<div class="person-gallery">${mediaGallery(p)}</div>`:""}${linkButtons(p,[["linkedin","LinkedIn"],["researchgate","ResearchGate"],["orcid","ORCID"],["website","Website"],["publications","Publication"]])}</article>`}
function groupRail(id,cards){return `<div class="group-rail-head"><div class="rail-controls"><button data-scroll="${id}" data-dir="-1" aria-label="Previous">←</button><button data-scroll="${id}" data-dir="1" aria-label="Next">→</button></div></div><div id="${id}" class="horizontal-rail group-rail auto-rail">${cards}</div>`}
function renderTeam(items){const el=document.getElementById("team-groups"),map=new Map();items.forEach(p=>{const g=memberGroup(p);if(!map.has(g.key))map.set(g.key,{...g,items:[]});map.get(g.key).items.push(p)});const groups=[...map.values()].sort((a,b)=>a.rank-b.rank);if(!groups.length)return empty(el,"Team members will appear here.");el.innerHTML=groups.map((g,i)=>{const id=`team-${g.key}-rail`,cards=g.items.map(p=>personCard(p)).join("");return `<details class="group-accordion" ${i===0?"open":""}><summary><span>${g.label}</span><span>${g.items.length}</span></summary><div class="group-content">${groupRail(id,cards)}</div></details>`}).join("");enhanceDynamicUI()}

const COUNTRY_FLAGS={chile:"🇨🇱",italy:"🇮🇹",italia:"🇮🇹",spain:"🇪🇸",españa:"🇪🇸",germany:"🇩🇪",alemania:"🇩🇪",france:"🇫🇷",francia:"🇫🇷",usa:"🇺🇸","united states":"🇺🇸",canada:"🇨🇦",brazil:"🇧🇷",brasil:"🇧🇷",argentina:"🇦🇷",peru:"🇵🇪",perú:"🇵🇪",ecuador:"🇪🇨",colombia:"🇨🇴",mexico:"🇲🇽",méxico:"🇲🇽",uk:"🇬🇧","united kingdom":"🇬🇧",portugal:"🇵🇹",australia:"🇦🇺",japan:"🇯🇵",japón:"🇯🇵"};
function countryFlag(country){return COUNTRY_FLAGS[safe(country).toLowerCase()]||"🌐"}
function renderCollaborations(national,international){const el=document.getElementById("collaboration-groups"),groups=[{key:"national",label:"National Collaborations",items:national},{key:"international",label:"International Collaborations",items:international}];el.innerHTML=groups.map(g=>{const id=`collab-${g.key}-rail`,cards=g.items.map(c=>personCard(c,countryFlag(c.country))).join("");return `<details class="group-accordion"><summary><span>${g.label}</span><span>${g.items.length}</span></summary><div class="group-content">${g.items.length?groupRail(id,cards):`<div class="empty-state">No collaborators added yet.</div>`}</div></details>`}).join("");enhanceDynamicUI()}

function renderEquipment(items){const el=document.getElementById("equipment-rail");if(!items.length)return empty(el,"Equipment will appear automatically when folders are added to /Equipment.");el.innerHTML=items.map(e=>`<article class="dynamic-card equipment-card">${getMedia(e).length?mediaGallery(e):`<div class="equipment-placeholder">◇</div>`}<div class="equipment-body"><h3>${esc(e.name)}</h3>${safe(e.model)?`<div class="person-role">${esc(e.model)}</div>`:""}${safe(e.summary)?`<p>${esc(e.summary)}</p>`:""}${linkButtons(e,[["link","More information"],["website","Website"],["publications","Publication"],["documentation","Documentation"]])}</div></article>`).join("");enhanceDynamicUI()}
function renderTechnologies(items){const el=document.getElementById("technologies-rail");if(!items.length)return empty(el,"Software and digital developments will appear automatically when folders are added to /Technologies.");el.innerHTML=items.map(t=>`<article class="dynamic-card technology-card">${getMedia(t).length?mediaGallery(t):`<div class="equipment-placeholder">${iconSVG("code")}</div>`}<div class="technology-body"><div class="card-top">${safe(t.type)?`<span class="tag">${esc(t.type)}</span>`:""}</div><h3>${esc(t.name)}</h3>${safe(t.version)?`<div class="person-role">Version ${esc(t.version)}</div>`:""}${safe(t.summary)?`<p>${esc(t.summary)}</p>`:""}${linkButtons(t,[["link","Open technology"],["repository","Repository"],["documentation","Documentation"],["publications","Publication"]])}</div></article>`).join("");enhanceDynamicUI()}
function renderResources(items){const el=document.getElementById("resources-rail");if(!items.length)return empty(el,"Manuals, classes and other resources will appear automatically when folders are added to /Resources.");el.innerHTML=items.map(r=>{const files=Array.isArray(r.downloads)&&r.downloads.length?r.downloads:splitValues(r.download);const fileLinks=files.map((f,i)=>`<a href="${esc(assetURL(f))}" target="_blank" rel="noopener noreferrer">${files.length>1?`File ${i+1}`:'Open file'} ↗</a>`).join("");return `<article class="dynamic-card resource-card">${getMedia(r).length?mediaGallery(r):`<div class="equipment-placeholder">${iconSVG("file")}</div>`}<div class="resource-body"><div class="card-top">${safe(r.type)?`<span class="tag">${esc(r.type)}</span>`:""}${safe(r.year)?`<span class="tag">${esc(r.year)}</span>`:""}</div><h3>${esc(r.name)}</h3>${safe(r.summary)?`<p>${esc(r.summary)}</p>`:""}${linkButtons(r,[["link","Open resource"],["publications","Publication"],["documentation","Documentation"]])}${fileLinks?`<div class="card-links">${fileLinks}</div>`:""}</div></article>`}).join("");enhanceDynamicUI()}

let PUBLICATIONS=[],PUB_SHOW_ALL=false;
function normalizeDOI(v){const doi=safe(v).replace(/^https?:\/\/(dx\.)?doi\.org\//i,"").replace(/^doi:\s*/i,"");return doi?`https://doi.org/${doi}`:""}
function populatePublicationFilters(items){setOptions(document.getElementById('publication-year'),[...new Set(items.map(x=>safe(x.year)).filter(Boolean))].sort((a,b)=>Number(b)-Number(a)),'All years');setOptions(document.getElementById('publication-journal'),uniqueValues(items,'journal'),'All journals');['publication-year','publication-journal'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{PUB_SHOW_ALL=false;renderPublicationsFiltered()}))}
function renderPublicationsFiltered(){const y=document.getElementById("publication-year").value,j=document.getElementById('publication-journal').value;let items=PUBLICATIONS.filter(p=>(y==="all"||safe(p.year)===y)&&(j==='all'||safe(p.journal)===j));items=[...items].sort((a,b)=>Number(b.year||0)-Number(a.year||0)||safe(a.name).localeCompare(safe(b.name)));const shown=PUB_SHOW_ALL?items:items.slice(0,3);renderPublications(shown);const btn=document.getElementById("publications-toggle");btn.style.display=items.length>3?"inline-flex":"none";btn.textContent=PUB_SHOW_ALL?"Show only latest 3 −":"View all publications +"}
function renderPublications(items){const el=document.getElementById("publications-list");el.scrollLeft=0;if(!items.length)return empty(el,"No publications match these filters.");el.innerHTML=items.map(p=>{const doi=normalizeDOI(p.doi),links=splitValues(p.link),actions=[];if(doi)actions.push(`<a href="${esc(doi)}" target="_blank" rel="noopener noreferrer">DOI ↗</a>`);links.filter(x=>x!==doi).forEach((x,i)=>actions.push(`<a href="${esc(assetURL(x))}" target="_blank" rel="noopener noreferrer">${links.length>1?`Link ${i+1}`:'Link'} ↗</a>`));return `<article class="publication-item"><div class="publication-year">${esc(p.year)}</div><div><div class="publication-title">${esc(p.name)}</div>${safe(p.authors)?`<div class="publication-authors">${esc(p.authors)}</div>`:""}${safe(p.journal)?`<div class="publication-journal">${esc(p.journal)}</div>`:""}</div><div class="publication-actions">${actions.join('')}</div></article>`}).join("");enhanceDynamicUI()}

function renderContact(c){const email=safe(c.email)||"syepez@udec.cl";document.getElementById("contact-email").textContent=email;document.getElementById("email-button").href=`mailto:${email}?subject=HydroGeoAI%20Lab%20-%20Contact&body=Hello%20HydroGeoAI%20Lab%2C%0A%0AI%20would%20like%20to%20contact%20you%20regarding%3A%0A%0A`;document.getElementById("contact-location").textContent=safe(c.location)||"Concepción, Chile";const lat=safe(c.latitude)||"-36.834495",lon=safe(c.longitude)||"-73.032547";document.getElementById("map-frame").src=`https://www.google.com/maps?q=${lat},${lon}&z=16&output=embed`;document.getElementById("map-link").href=safe(c.maplink)||"https://maps.app.goo.gl/EthMW9VcD7aecfzE7";const socials=[["instagram","Instagram"],["facebook","Facebook"],["linkedin","LinkedIn"],["youtube","YouTube"],["x","X"],["researchgate","ResearchGate"],["website","Website"]];document.getElementById("social-links").innerHTML=socials.filter(([k])=>safe(c[k])).map(([k,l])=>`<a href="${esc(c[k])}" target="_blank" rel="noopener noreferrer">${l} ↗</a>`).join("")}

function setupRails(){document.querySelectorAll("[data-scroll]").forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound="1";btn.addEventListener("click",()=>{const rail=document.getElementById(btn.dataset.scroll);if(!rail)return;rail.dataset.userPause=String(Date.now()+9000);rail.scrollBy({left:Number(btn.dataset.dir)*Math.max(320,rail.clientWidth*.72),behavior:"smooth"})})})}
const autoRailTimers=new WeakMap();
function setupAutoRails(){document.querySelectorAll('.auto-rail,.group-rail').forEach(rail=>{if(autoRailTimers.has(rail))return;let hover=false;rail.addEventListener('mouseenter',()=>hover=true);rail.addEventListener('mouseleave',()=>hover=false);rail.addEventListener('touchstart',()=>{rail.dataset.userPause=String(Date.now()+10000)},{passive:true});rail.addEventListener('pointerdown',()=>{rail.dataset.userPause=String(Date.now()+10000)});const timer=setInterval(()=>{if(document.hidden||hover||Date.now()<Number(rail.dataset.userPause||0)||rail.scrollWidth<=rail.clientWidth+10)return;const first=rail.firstElementChild;if(!first)return;const step=first.getBoundingClientRect().width+20;const atEnd=rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-12;rail.scrollTo({left:atEnd?0:rail.scrollLeft+step,behavior:'smooth'})},4300);autoRailTimers.set(rail,timer)})}
function setupMediaCarousels(){document.querySelectorAll('[data-media-carousel]').forEach(car=>{if(car.dataset.bound)return;car.dataset.bound='1';const slides=[...car.querySelectorAll('.media-slide')];if(slides.length<2)return;let index=0,hover=false;const counter=car.querySelector('.media-inline-counter span');const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>{s.classList.toggle('active',i===index);if(s.tagName==='VIDEO'){if(i===index)s.play().catch(()=>{});else s.pause()}});if(counter)counter.textContent=index+1};car.querySelector('.media-inline-prev')?.addEventListener('click',e=>{e.stopPropagation();car.dataset.pause=String(Date.now()+8000);show(index-1)});car.querySelector('.media-inline-next')?.addEventListener('click',e=>{e.stopPropagation();car.dataset.pause=String(Date.now()+8000);show(index+1)});car.addEventListener('mouseenter',()=>hover=true);car.addEventListener('mouseleave',()=>hover=false);setInterval(()=>{if(document.hidden||hover||Date.now()<Number(car.dataset.pause||0))return;show(index+1)},5000);show(0)})}
function enhanceDynamicUI(){setupRails();setupAutoRails();setupMediaCarousels()}

function setupMediaModal(){const modal=document.getElementById("media-modal"),stage=document.getElementById("media-stage"),close=document.getElementById("media-close");let gallery=[],idx=0;function show(){const m=gallery[idx];if(!m)return;stage.innerHTML=`<button class="modal-nav modal-prev" aria-label="Previous">‹</button>${m.type==="video"?`<video src="${esc(assetURL(m.src))}" controls autoplay></video>`:`<img src="${esc(assetURL(m.src))}" alt="Expanded media">`}<button class="modal-nav modal-next" aria-label="Next">›</button><div class="modal-counter">${idx+1} / ${gallery.length}</div>`;stage.querySelector('.modal-prev').onclick=()=>{idx=(idx-1+gallery.length)%gallery.length;show()};stage.querySelector('.modal-next').onclick=()=>{idx=(idx+1)%gallery.length;show()}}
function open(items,start=0){gallery=items;idx=Math.max(0,Math.min(start,items.length-1));show();modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function shut(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");stage.innerHTML="";document.body.style.overflow=""}
document.addEventListener("click",e=>{const t=e.target;if(t.matches(".media-clickable")){try{open(JSON.parse(t.dataset.gallery||'[]'),Number(t.dataset.index||0))}catch{open([{src:t.currentSrc||t.src,type:t.tagName==='VIDEO'?'video':'image'}],0)}}else if(t.matches(".zoomable")){open([{src:t.currentSrc||t.src,type:t.tagName==="VIDEO"?"video":"image"}],0)}});close.addEventListener("click",shut);modal.addEventListener("click",e=>{if(e.target===modal)shut()});document.addEventListener("keydown",e=>{if(!modal.classList.contains('open'))return;if(e.key==='Escape')shut();if(e.key==='ArrowLeft'){idx=(idx-1+gallery.length)%gallery.length;show()}if(e.key==='ArrowRight'){idx=(idx+1)%gallery.length;show()}})}

function animateCounter(id,target){const el=document.getElementById(id);if(!el)return;target=Number(target)||0;const duration=750,start=performance.now();const tick=now=>{const p=Math.min(1,(now-start)/duration);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
function renderCounters({projects,publications,team,national,international,technologies,courses}){animateCounter('stat-projects',projects.length);animateCounter('stat-publications',publications.length);animateCounter('stat-team',team.length);animateCounter('stat-collaborations',national.length+international.length);animateCounter('stat-technologies',technologies.length);animateCounter('stat-courses',courses.length)}

async function init(){
  const [about,news,projects,services,courses,team,national,international,equipment,technologies,resources,publications,contact]=await Promise.all([
    getJSON(DATA.about,{}),getJSON(DATA.news),getJSON(DATA.projects),getJSON(DATA.services),getJSON(DATA.courses),
    getJSON(DATA.team),getJSON(DATA.national),getJSON(DATA.international),getJSON(DATA.equipment),getJSON(DATA.technologies),
    getJSON(DATA.resources),getJSON(DATA.publications),getJSON(DATA.contact,{})
  ]);
  renderAbout(about);
  NEWS=news;populateNewsFilters(NEWS);renderNewsFiltered();
  PROJECTS=projects;populateProjectFilters(PROJECTS);renderProjectsFiltered();
  SERVICES=services;populateServiceFilters(SERVICES);renderServicesFiltered();
  COURSES=courses;populateCourseFilters(COURSES);renderCoursesFiltered();
  renderTeam(team);renderCollaborations(national,international);renderEquipment(equipment);renderTechnologies(technologies);renderResources(resources);
  PUBLICATIONS=publications;populatePublicationFilters(PUBLICATIONS);renderPublicationsFiltered();document.getElementById("publications-toggle").addEventListener("click",()=>{PUB_SHOW_ALL=!PUB_SHOW_ALL;renderPublicationsFiltered()});
  renderContact(contact);renderCounters({projects,publications,team,national,international,technologies,courses});setupMediaModal();enhanceDynamicUI();
}
init();
